checks:
    php: true

filter:
    paths:
        - "src/*"

build:
    nodes:
        analysis:
            services:
                memcached:
                    image: memcached:latest
                    ports:
                        11211

            environment:
                php: 7.4.12

            dependencies:
                override:
                    - pecl install memcached

            tests:
                override:
                    - php-scrutinizer-run

        tests-and-coverage:
            services:
                memcached:
                    image: memcached:latest
                    ports:
                        11211

            environment:
                php: 7.4.12

            dependencies:
                override:
                    - composer self-update
                    - pecl install memcached
                    - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            tests:
                override:
                    -
                        command: "./vendor/bin/phpunit --coverage-clover ./coverage.xml"
                        on_node: 1
                        coverage:
                            file: coverage.xml
                            format: php-clover
